#spring.application.name=time-flow
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/timeflow
#spring.datasource.username=pengqixiang
#spring.datasource.password=
#
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


spring.application.name=time-flow

spring.datasource.url=jdbc:postgresql://localhost:5432/timeflow
spring.datasource.username=pengqixiang
spring.datasource.password=

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.hibernate.formate_sql=true
